# Generated by Django 2.2.4 on 2020-05-05 11:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='choice_of_trade',
            field=otree.db.models.BooleanField(choices=[[True, 'køb (long)'], [False, 'lån og sælg (short)']], default=True, null=True),
        ),
    ]
