# Generated by Django 2.2.4 on 2020-05-05 13:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0003_auto_20200505_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='price',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='price_change',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='wallet',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
