# Generated by Django 2.2.4 on 2020-05-05 14:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0011_auto_20200505_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='choice_of_trade',
            field=otree.db.models.IntegerField(choices=[[2, 'gør ingenting'], [True, 'køb (long)'], [False, 'lån og sælg (short)']], null=True),
        ),
    ]
