# Generated by Django 2.2.4 on 2020-05-05 15:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0013_auto_20200505_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='choice_of_trade',
            field=otree.db.models.IntegerField(choices=[[2, 'gør ingenting'], [1, 'køb (long)'], [0, 'lån og sælg (short)']], null=True),
        ),
    ]
