# Generated by Django 2.2.4 on 2020-05-13 12:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0002_auto_20200504_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='choice_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
