# Generated by Django 2.2.4 on 2020-05-13 13:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0003_player_choice_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='preference_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
