# Generated by Django 2.2.4 on 2020-05-13 13:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0004_player_preference_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='payoff',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
