# Generated by Django 2.2.4 on 2020-05-13 13:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0005_player_payoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='payoff',
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
