# Generated by Django 2.2.4 on 2020-05-13 14:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0006_auto_20200513_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points_total',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
