# Generated by Django 2.2.4 on 2020-05-13 14:48

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0007_player_points_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fulgt_flertallet_pct',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fulgt_preference_pct',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
    ]
