# Generated by Django 2.2.4 on 2020-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_chat_color',
        ),
        migrations.AlterField(
            model_name='group',
            name='choice',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='consensus',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='round_end_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='round_start_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='choice',
            field=models.BooleanField(choices=[[True, 'Rød'], [False, 'Blå']], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='hub',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='last_choice_made_at',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='number_of_friends',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsession',
            name='consensus',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
