# Generated by Django 2.2.4 on 2020-04-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0002_auto_20200413_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
