# Generated by Django 2.2.4 on 2020-04-13 19:14

from django.db import migrations, models
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0003_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='choice',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='consensus',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='round_end_time',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='round_start_time',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='choice',
            field=otree.db.models.BooleanField(choices=[[True, 'Rød'], [False, 'Blå']], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hub',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_choice_made_at',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='number_of_friends',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subsession',
            name='consensus',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
