# Generated by Django 2.2.4 on 2020-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0004_auto_20200413_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
