# Generated by Django 2.2.4 on 2020-04-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0007_player_chat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daytrader.Player'),
            preserve_default=False,
        ),
    ]
