# Generated by Django 2.2.4 on 2020-04-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0008_message_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='player',
        ),
    ]
