# Generated by Django 2.2.4 on 2020-04-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0010_message_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_influence.Player'),
        ),
    ]
