# Generated by Django 2.2.4 on 2020-04-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0011_auto_20200420_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
