# Generated by Django 2.2.4 on 2020-04-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0013_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='player',
        ),
    ]
