# Generated by Django 2.2.4 on 2020-04-22 10:37

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('daytrader', '0017_auto_20200421_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=otree.db.models.LongStringField(null=True),
        ),
        migrations.AlterModelTable(
            name='message',
            table='bad_influence_message',
        ),
    ]
