# Generated by Django 2.2.4 on 2020-06-02 14:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0019_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='choice_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fulgt_flertallet_pct',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fulgt_preference_pct',
            field=otree.db.models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='points_total',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='preference_str',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
