# Generated by Django 2.2.4 on 2020-06-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_influence', '0020_auto_20200602_1400'),
        ('bad_influence', '0020_auto_20200609_1400'),
    ]

    operations = [
    ]
