SubsessionClass = 'SubsessionClass'
GroupClass = 'GroupClass'
PlayerClass = 'PlayerClass'
UserClass = 'UserClass'

group_id = 'group_id'

user_code = 'user_code'
subsession_code = 'subsession_code'
subsession_code_obfuscated = 'exp_code'

nickname = 'nickname'

completed_views = 'completed_views'

form_invalid = 'form_invalid'
precondition = 'precondition'
mturk_assignment_id = 'mturk_assignment_id'
mturk_worker_id = 'mturk_worker_id'
debug_values_built_in = 'debug_values_built_in'
debug_values = 'debug_values'
check_if_wait_is_over = 'check_if_wait_is_over'
get_param_truth_value = '1'
experimenter_access_code = 'experimenter_access_code'
index_in_pages = 'index_in_pages'

time_limit_in_seconds = 'time_limit_in_seconds'
time_limit_minutes_component = 'time_limit_minutes_component'
time_limit_seconds_component = 'time_limit_seconds_component'
page_expiration_times = 'page_time_limits'
participant_label = 'participant_label'
session_access_code = 'session_access_code'
form_element_id = 'form'
session_user_id = 'session_user_id'
session_user_code = 'session_user_code'
session_id = 'session_id'
session_code = 'session_code'
wait_page_http_header = 'oTree-Wait-Page'
redisplay_with_errors_http_header = 'oTree-Redisplay-With-Errors'
user_type = 'user_type'
user_type_participant = 'p'
user_type_experimenter = 'e'
success = True
failure = False
special_category_bots = 'bots'
special_category_demo = 'demo'
access_code_for_open_session = 'access_code_for_open_session'